IAM_STAFF_APP_HOST="0.0.0.0"
IAM_STAFF_APP_PORT=8000

IAM_STAFF_AUTH_REDIS_URL="redis://redis:6379/0"
IAM_STAFF_AUTH_TRANSACTION_STORE_BACKEND=redis

IAM_STAFF_DB_DRIVER=postgresql+asyncpg
IAM_STAFF_DB_HOSTNAME="postgres"
IAM_STAFF_DB_USERNAME=postgres
IAM_STAFF_DB_PASSWORD="{{POSTGRES_PASSWORD}}"
IAM_STAFF_DB_DBNAME=iam_staff
IAM_STAFF_DB_PORT=5432

IAM_STAFF_OPENAPI_ROOT_PATH=/
IAM_STAFF_LOGIN_PROVIDERS_TABLE_ENABLED=true
IAM_STAFF_AUTH_ENABLED=true
IAM_STAFF_AUTH_COOKIE_HTTPONLY=true
IAM_STAFF_AUTH_COOKIE_PATH=/
IAM_STAFF_AUTH_COOKIE_DOMAIN=localhost
IAM_STAFF_AUTH_COOKIE_MAX_AGE=1800
IAM_STAFF_AUTH_COOKIE_SET_EXPIRES=true
IAM_STAFF_AUTH_COOKIE_SECURE=false

IAM_STAFF_DATA_DIR="/opt/iam-staff-portal-data"
IAM_STAFF_DATA_APPLICATION_URLS__KEYCLOAK_APPLICATION_URL="{{KEYCLOAK_URL}}"
IAM_STAFF_DATA_APPLICATION_URLS__REGISTRY_APPLICATION_URL="http://localhost:{{NSR_REGISTRY_STAFF_API_PORT}}"
IAM_STAFF_DATA_APPLICATION_URLS__MINIO_APPLICATION_URL="http://{{MINIO_ENDPOINT}}"
IAM_STAFF_DATA_CLIENT_SECRETS__STAFF_KEYCLOAK_CLIENT_SECRET="{{KEYCLOAK_IAM_CLIENT_SECRET}}"

IAM_STAFF_CORS_ALLOW_ORIGINS='["*"]'
