GEN2_MASTER_DATA_API_HOST="0.0.0.0"
GEN2_MASTER_DATA_API_PORT=8000
GEN2_MASTER_DATA_API_NO_OF_WORKERS=2
GEN2_MASTER_DATA_API_OPENAPI_ROOT_PATH=/
GEN2_MASTER_DATA_API_WORKER_TYPE=gunicorn

GEN2_MASTER_DATA_API_DB_DRIVER="postgresql+asyncpg"
GEN2_MASTER_DATA_API_DB_HOSTNAME="postgres"
GEN2_MASTER_DATA_API_DB_PORT=5432
GEN2_MASTER_DATA_API_DB_USERNAME="postgres"
GEN2_MASTER_DATA_API_DB_PASSWORD="{{POSTGRES_PASSWORD}}"
GEN2_MASTER_DATA_API_DB_DBNAME="{{REGISTRY_MASTER_DATA_DB_NAME}}"

# iam-core auth middleware (COMMON_*). Ping stays public; API routes may require IAM.
COMMON_AUTH_ENABLED="false"
COMMON_AUTH_PROVIDER_API_URL="http://iam-staff-api:8000"
COMMON_KEYCLOAK_CLIENT_ID="{{REGISTRY_KEYCLOAK_CLIENT_ID}}"
COMMON_AUTH_REDIS_URL="redis://redis:6379/0"
COMMON_AUTH_VERIFY_SSL="false"
