GEN2_MASTER_DATA_API_HOST="0.0.0.0"
GEN2_MASTER_DATA_API_PORT={{MASTER_DATA_API_PORT}}
GEN2_MASTER_DATA_API_NO_OF_WORKERS=1
GEN2_MASTER_DATA_API_OPENAPI_ROOT_PATH=/
# local = uvicorn.run(app) in-process. "uvicorn"/"gunicorn" shell out to
# main:app, but master-data-api has no repo-root main.py (package path only).
GEN2_MASTER_DATA_API_WORKER_TYPE=local

GEN2_MASTER_DATA_API_DB_DRIVER="postgresql+asyncpg"
GEN2_MASTER_DATA_API_DB_HOSTNAME="{{POSTGRES_HOST}}"
GEN2_MASTER_DATA_API_DB_PORT={{POSTGRES_PORT}}
GEN2_MASTER_DATA_API_DB_USERNAME="postgres"
GEN2_MASTER_DATA_API_DB_PASSWORD="{{POSTGRES_PASSWORD}}"
GEN2_MASTER_DATA_API_DB_DBNAME="{{REGISTRY_MASTER_DATA_DB_NAME}}"

# iam-core auth middleware (COMMON_*). Keep false for local registry e2e.
COMMON_AUTH_ENABLED="false"
COMMON_AUTH_PROVIDER_API_URL="http://localhost:{{IAM_STAFF_PORT}}"
COMMON_KEYCLOAK_CLIENT_ID="{{REGISTRY_KEYCLOAK_CLIENT_ID}}"
COMMON_AUTH_REDIS_URL="redis://{{REDIS_HOST}}:{{REDIS_PORT}}/0"
COMMON_AUTH_VERIFY_SSL="false"

UVICORN_HOST="0.0.0.0"
UVICORN_PORT={{MASTER_DATA_API_PORT}}
