REGISTRY_PARTNER_API_PORT={{REGISTRY_PARTNER_API_PORT}}
REGISTRY_PARTNER_API_APP_HOST="0.0.0.0"
REGISTRY_PARTNER_API_APP_PORT={{REGISTRY_PARTNER_API_PORT}}
REGISTRY_PARTNER_API_DB_DRIVER="postgresql+asyncpg"
REGISTRY_PARTNER_API_DB_USERNAME="postgres"
REGISTRY_PARTNER_API_DB_PASSWORD="{{POSTGRES_PASSWORD}}"
REGISTRY_PARTNER_API_DB_HOSTNAME="{{POSTGRES_HOST}}"
REGISTRY_PARTNER_API_DB_PORT={{POSTGRES_PORT}}
REGISTRY_PARTNER_API_DB_DBNAME="{{REGISTRY_DB_NAME}}"

REGISTRY_PARTNER_API_MINIO_ENDPOINT="{{MINIO_ENDPOINT}}"
REGISTRY_PARTNER_API_MINIO_ACCESS_KEY="{{MINIO_ROOT_USER}}"
REGISTRY_PARTNER_API_MINIO_SECRET_KEY="{{MINIO_ROOT_PASSWORD}}"
REGISTRY_PARTNER_API_MINIO_SECURE="false"
REGISTRY_PARTNER_API_DOCUMENT_STORAGE_BACKEND="minio"
REGISTRY_PARTNER_API_MINIO_BUCKET_NAME="default_bucket"
REGISTRY_PARTNER_API_TEMPLATE_BUCKET_NAME="templates"

REGISTRY_PARTNER_API_MASTER_DATA_DB_DRIVER="postgresql+asyncpg"
REGISTRY_PARTNER_API_MASTER_DATA_DB_USERNAME="postgres"
REGISTRY_PARTNER_API_MASTER_DATA_DB_PASSWORD="{{POSTGRES_PASSWORD}}"
REGISTRY_PARTNER_API_MASTER_DATA_DB_HOSTNAME="{{POSTGRES_HOST}}"
REGISTRY_PARTNER_API_MASTER_DATA_DB_PORT={{POSTGRES_PORT}}
REGISTRY_PARTNER_API_MASTER_DATA_DB_DBNAME="{{REGISTRY_MASTER_DATA_DB_NAME}}"

REGISTRY_PARTNER_API_KEYMANAGER_AUTH_ENABLED="false"
REGISTRY_PARTNER_API_AUDIT_ENABLED="false"
REGISTRY_PARTNER_API_OPENAPI_ROOT_PATH="/"
REGISTRY_PARTNER_API_CORS_ALLOW_ORIGINS='["*"]'
